[package]
name = "rust-git"
version = "0.1.0"
authors = ["Jacob Meyers <jacobmeyers065@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
regex = "1.3.4"
rust-ini = "0.15.2"
sha2 = "0.8.1"